In [ ]:
import pandas as pd

data = {
    'Name': ['John', 'Anna', 'Mike', 'Sara', 'John'],
    'Age': [23, 25, 22, 24, 23],
    'Marks': [85, 90, 78, 88, 85]
}

In [ ]:
df = pd.DataFrame(data)
print(df)

   Name  Age  Marks
0  John   23     85
1  Anna   25     90
2  Mike   22     78
3  Sara   24     88
4  John   23     85

In [ ]:
print(df.head())

   Name  Age  Marks
0  John   23     85
1  Anna   25     90
2  Mike   22     78
3  Sara   24     88
4  John   23     85

In [ ]:
print(df.tail())

   Name  Age  Marks
0  John   23     85
1  Anna   25     90
2  Mike   22     78
3  Sara   24     88
4  John   23     85

In [ ]:
print(df.shape)

(5, 3)

In [ ]:
print("\nColumn Names:")
print(df.columns)

Column Names:
Index(['Name', 'Age', 'Marks'], dtype='object')

In [ ]:
print("\nDataset Information:")
print(df.info())

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   Marks   5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes
None

In [ ]:
print("\nStatistical Summary:")
print(df.describe())

Statistical Summary:
             Age      Marks
count   5.000000   5.000000
mean   23.400000  85.200000
std     1.140175   4.549725
min    22.000000  78.000000
25%    23.000000  85.000000
50%    23.000000  85.000000
75%    24.000000  88.000000
max    25.000000  90.000000

In [ ]:
print("\nAfter Removing Duplicates:")
print(df.drop_duplicates())

After Removing Duplicates:
   Name  Age  Marks
0  John   23     85
1  Anna   25     90
2  Mike   22     78
3  Sara   24     88

In [ ]:
print(df.sort_values(by='Marks'))

   Name  Age  Marks
2  Mike   22     78
0  John   23     85
4  John   23     85
3  Sara   24     88
1  Anna   25     90

In [ ]:
print(df.isnull())

    Name    Age  Marks
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False

In [ ]:
print(df.notnull())

   Name   Age  Marks
0  True  True   True
1  True  True   True
2  True  True   True
3  True  True   True
4  True  True   True

In [ ]:
print(df.duplicated())

0    False
1    False
2    False
3    False
4     True
dtype: bool

In [ ]:
print(df.sample())

   Name  Age  Marks
2  Mike   22     78

In [ ]:
print(df.rename(columns={"Marks":"Score"}))

   Name  Age  Score
0  John   23     85
1  Anna   25     90
2  Mike   22     78
3  Sara   24     88
4  John   23     85

In [ ]:
print(df["Marks"].mean())

85.2

In [ ]:
print(df["Marks"].sum())

426

In [ ]:
print(df["Marks"].min())

78

In [ ]:
print(df["Marks"].max())

90

In [ ]:
print(df["Marks"].count())

5

In [ ]:
print(df["Marks"].var())

20.700000000000003

In [ ]:
print(df["Marks"].median())

85.0

In [ ]:
df

   Name  Age  Marks
0  John   23     85
1  Anna   25     90
2  Mike   22     78
3  Sara   24     88
4  John   23     85

In [ ]:
print(df.groupby("Name").sum())

      Age  Marks
Name
Anna   25     90
John   46    170
Mike   22     78
Sara   24     88

In [ ]:
df.insert(1, "Roll.No", [101, 102, 103, 104, 105])

print(df)

   Name  Roll.No  Age  Marks
0  John      101   23     85
1  Anna      102   25     90
2  Mike      103   22     78
3  Sara      104   24     88
4  John      105   23     85

In [ ]:
df = df.drop("Roll.No", axis = 1)
print(df)

   Name  Age  Marks
0  John   23     85
1  Anna   25     90
2  Mike   22     78
3  Sara   24     88
4  John   23     85

In [ ]:
new = df.copy()
print(new)

   Name  Age  Marks
0  John   23     85
1  Anna   25     90
2  Mike   22     78
3  Sara   24     88
4  John   23     85

In [ ]:
import pandas as pd

data = {
    "Date": ["2026-05-20", "2026-05-21", "2026-05-22"]
}

df = pd.DataFrame(data)

df["Date"] = pd.to_datetime(df["Date"])

print(df)

        Date
0 2026-05-20
1 2026-05-21
2 2026-05-22

In [ ]:
import pandas as pd

data = {
    "Grade": ["A", "B", "C", "A"]
}

df = pd.DataFrame(data)

result = df["Grade"].map({
    "A": "Excellent",
    "B": "Good",
    "C": "Average"
})

print(result)

0    Excellent
1         Good
2      Average
3    Excellent
Name: Grade, dtype: object

In [ ]:
import pandas as pd

df1 = pd.DataFrame({
    "Name": ["Pooja", "Monesh"],
    "Marks": [90, 85]
})

df2 = pd.DataFrame({
    "Name": ["Karishma", "Immanaeul"],
    "Marks": [88, 92]
})

result = pd.concat([df1, df2])

print(result)

        Name  Marks
0      Pooja     90
1     Monesh     85
0   Karishma     88
1  Immanaeul     92

In [ ]:
import pandas as pd

df1 = pd.DataFrame({
    "ID": [1, 2, 3],
    "Name": ["Pooja", "Ravi", "Anu"]
})

df2 = pd.DataFrame({
    "ID": [1, 2, 3],
    "Marks": [90, 85, 88]
})

result = pd.merge(df1, df2, on="ID")

print(result)

   ID   Name  Marks
0   1  Pooja     90
1   2   Ravi     85
2   3    Anu     88

In [ ]:
df=pd.read_excel('/content/Datasets_Finance.xlsx')

In [ ]:
df

,Applicant ID,Applicant Age,Graduate/Non-Graduate,Employed/Unemployed,Salary,Loan Amount,Cibil Score,Loan Duration,Paying Bills,Existing Loan,Co - Applicant ID,Co - Applicant Age,Co - Applicant Salary,Loan Approved / Rejected
0,A101,28,Graduate,Employed,50000,150000,780,12 Months,Yes,No,B101,26,25000,Approved
1,A102,35,Non-Graduate,Unemployed,18000,300000,580,36 Months,No,Yes,B102,40,10000,Rejected
2,A103,42,Graduate,Employed,62000,200000,750,18 Months,Yes,No,B103,30,22000,Approved
3,A104,50,Non-Graduate,Self Employed,22000,350000,540,48 Motnhs,No,Yes,B104,45,12000,Rejected
4,A105,29,Graduate,Employed,70000,120000,810,12 Months,Yes,No,B105,27,30000,Approved
5,A106,41,Graduate,Self Employed,26000,280000,590,30 Months,No,Yes,B106,38,15000,Rejected
6,A107,35,Graduate,Employed,58000,170000,770,15 Months,Yes,No,B107,31,24000,Approved
7,A108,48,Non-Graduate,Unemployed,20000,320000,560,40 Months,No,Yes,B108,42,9000,Rejected
8,A109,30,Graduate,Employed,65000,140000,790,10 Months,Yes,No,B109,28,26000,Approved
9,A110,46,Non-Graduate,Self Employed,24000,290000,570,36 Months,No,Yes,B110,43,11000,Rejected
10,A111,33,Graduate,Employed,80000,100000,830,12 Months,Yes,No,B111,29,35000,Approved
11,A112,44,Non-Graduate,Unemployed,21000,310000,550,24 Months,No,Yes,B112,39,10000,Rejected
12,A113,27,Graduate,Employed,60000,160000,760,18 Months,Yes,No,B113,25,20000,Approved
13,A114,52,Non-Graduate,Self Employed,19000,340000,530,42 Months,No,Yes,B114,46,8000,Rejected
14,A115,31,Graduate,Employed,72000,130000,800,12 Months,Yes,No,B115,28,28000,Approved
15,A116,43,Graduate,Self Employed,25000,270000,600,30 Months,No,Yes,B116,37,30000,Rejected
16,A117,29,Graduate,Employed,61000,180000,785,20 Months,Yes,No,B117,27,23000,Approved
17,A118,49,Non-Graduate,Unemployed,23000,330000,545,38 Months,No,Yes,B118,44,9500,Rejected
18,A119,34,Graduate,Employed,770000,110000,820,12 Months,Yes,No,B119,30,32000,Approved
19,A120,47,Non-Graduate,Self Employed,22000,295000,565,36 Months,No,Yes,B120,41,10500,Rejected