In [ ]:
import pandas as pd
df = pd.read_excel('/content/Student.xlsx')

In [ ]:
df

  Student Name  Sub1  Sub2
0        Pooja    99    98
1       Monesh    98    99
2     Karishma    97    98
3     Immaenul    98    97

In [ ]:
df.insert(3, "Sub3", [95, 96, 97, 98])
print(df)

  Student Name  Sub1  Sub2  Sub3
0        Pooja    99    98    95
1       Monesh    98    99    96
2     Karishma    97    98    97
3     Immaenul    98    97    98

In [ ]:
df.loc[len(df)] = ["Roshan", 99, 99, 99]

In [ ]:
df

  Student Name  Sub1  Sub2  Sub3
0        Pooja    99    98    95
1       Monesh    98    99    96
2     Karishma    97    98    97
3     Immaenul    98    97    98
4       Roshan    99    99    99

In [ ]:
df

  Student Name  Sub2
0        Pooja    98
1       Monesh    99
2     Karishma    98
3     Immaenul    97
4       Roshan    99

In [ ]:
df = df.drop("Sub2", axis = 1)
print(df)

KeyError: "['Sub2'] not found in axis"