In [ ]:
import pandas as pd
df = pd.read_excel('/content/loan_approval_dataset.xlsx')

In [ ]:
df

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,2,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,4,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4264,4265,5,Graduate,Yes,1000000,2300000,12,317,2800000,500000,3300000,800000,Rejected
4265,4266,0,Not Graduate,Yes,3300000,11300000,20,559,4200000,2900000,11000000,1900000,Approved
4266,4267,2,Not Graduate,No,6500000,23900000,18,457,1200000,12400000,18100000,7300000,Rejected
4267,4268,1,Not Graduate,No,4100000,12800000,8,780,8200000,700000,14100000,5800000,Approved
4268,4269,1,Graduate,No,9200000,29700000,10,607,17800000,11800000,35700000,12000000,Approved

In [ ]:
print(df.head())

   loan_id  no_of_dependents      education  self_employed   income_annum  \
0        1                 2       Graduate             No        9600000
1        2                 0   Not Graduate            Yes        4100000
2        3                 3       Graduate             No        9100000
3        4                 3       Graduate             No        8200000
4        5                 5   Not Graduate            Yes        9800000

    loan_amount   loan_term   cibil_score   residential_assets_value  \
0      29900000          12           778                    2400000
1      12200000           8           417                    2700000
2      29700000          20           506                    7100000
3      30700000           8           467                   18200000
4      24200000          20           382                   12400000

    commercial_assets_value   luxury_assets_value   bank_asset_value  \
0                  17600000              22700000            8000000
1                   2200000               8800000            3300000
2                   4500000              33300000           12800000
3                   3300000              23300000            7900000
4                   8200000              29400000            5000000

   loan_status
0     Approved
1     Rejected
2     Rejected
3     Rejected
4     Rejected

In [ ]:
print(df.tail())

      loan_id  no_of_dependents      education  self_employed   income_annum  \
4264     4265                 5       Graduate            Yes        1000000
4265     4266                 0   Not Graduate            Yes        3300000
4266     4267                 2   Not Graduate             No        6500000
4267     4268                 1   Not Graduate             No        4100000
4268     4269                 1       Graduate             No        9200000

       loan_amount   loan_term   cibil_score   residential_assets_value  \
4264       2300000          12           317                    2800000
4265      11300000          20           559                    4200000
4266      23900000          18           457                    1200000
4267      12800000           8           780                    8200000
4268      29700000          10           607                   17800000

       commercial_assets_value   luxury_assets_value   bank_asset_value  \
4264                    500000               3300000             800000
4265                   2900000              11000000            1900000
4266                  12400000              18100000            7300000
4267                    700000              14100000            5800000
4268                  11800000              35700000           12000000

      loan_status
4264     Rejected
4265     Approved
4266     Rejected
4267     Approved
4268     Approved

In [ ]:
print(df.shape)

(4269, 13)

In [ ]:
print("\nColumn Names:")
print(df.columns)

Column Names:
Index(['loan_id', 'no_of_dependents', ' education', ' self_employed',
       ' income_annum', ' loan_amount', ' loan_term', ' cibil_score',
       ' residential_assets_value', ' commercial_assets_value',
       ' luxury_assets_value', ' bank_asset_value', ' loan_status'],
      dtype='object')

In [ ]:
print("\nDataset Information:")
print(df.info())

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4269 entries, 0 to 4268
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   loan_id                    4269 non-null   int64
 1   no_of_dependents           4269 non-null   int64
 2    education                 4269 non-null   object
 3    self_employed             4269 non-null   object
 4    income_annum              4269 non-null   int64
 5    loan_amount               4269 non-null   int64
 6    loan_term                 4269 non-null   int64
 7    cibil_score               4269 non-null   int64
 8    residential_assets_value  4269 non-null   int64
 9    commercial_assets_value   4269 non-null   int64
 10   luxury_assets_value       4269 non-null   int64
 11   bank_asset_value          4269 non-null   int64
 12   loan_status               4269 non-null   object
dtypes: int64(10), object(3)
memory usage: 433.7+ KB
None

In [ ]:
print("\nStatistical Summary:")
print(df.describe())

Statistical Summary:
           loan_id  no_of_dependents   income_annum   loan_amount  \
count  4269.000000       4269.000000   4.269000e+03  4.269000e+03
mean   2135.000000          2.498712   5.059124e+06  1.513345e+07
std    1232.498479          1.695910   2.806840e+06  9.043363e+06
min       1.000000          0.000000   2.000000e+05  3.000000e+05
25%    1068.000000          1.000000   2.700000e+06  7.700000e+06
50%    2135.000000          3.000000   5.100000e+06  1.450000e+07
75%    3202.000000          4.000000   7.500000e+06  2.150000e+07
max    4269.000000          5.000000   9.900000e+06  3.950000e+07

         loan_term   cibil_score   residential_assets_value  \
count  4269.000000   4269.000000               4.269000e+03
mean     10.900445    599.936051               7.472617e+06
std       5.709187    172.430401               6.503637e+06
min       2.000000    300.000000              -1.000000e+05
25%       6.000000    453.000000               2.200000e+06
50%      10.000000    600.000000               5.600000e+06
75%      16.000000    748.000000               1.130000e+07
max      20.000000    900.000000               2.910000e+07

        commercial_assets_value   luxury_assets_value   bank_asset_value
count              4.269000e+03          4.269000e+03       4.269000e+03
mean               4.973155e+06          1.512631e+07       4.976692e+06
std                4.388966e+06          9.103754e+06       3.250185e+06
min                0.000000e+00          3.000000e+05       0.000000e+00
25%                1.300000e+06          7.500000e+06       2.300000e+06
50%                3.700000e+06          1.460000e+07       4.600000e+06
75%                7.600000e+06          2.170000e+07       7.100000e+06
max                1.940000e+07          3.920000e+07       1.470000e+07

In [ ]:
print("\nAfter Removing Duplicates:")
print(df.drop_duplicates())

After Removing Duplicates:
      loan_id  no_of_dependents      education  self_employed   income_annum  \
0           1                 2       Graduate             No        9600000
1           2                 0   Not Graduate            Yes        4100000
2           3                 3       Graduate             No        9100000
3           4                 3       Graduate             No        8200000
4           5                 5   Not Graduate            Yes        9800000
...       ...               ...            ...            ...            ...
4264     4265                 5       Graduate            Yes        1000000
4265     4266                 0   Not Graduate            Yes        3300000
4266     4267                 2   Not Graduate             No        6500000
4267     4268                 1   Not Graduate             No        4100000
4268     4269                 1       Graduate             No        9200000

       loan_amount   loan_term   cibil_score   residential_assets_value  \
0         29900000          12           778                    2400000
1         12200000           8           417                    2700000
2         29700000          20           506                    7100000
3         30700000           8           467                   18200000
4         24200000          20           382                   12400000
...            ...         ...           ...                        ...
4264       2300000          12           317                    2800000
4265      11300000          20           559                    4200000
4266      23900000          18           457                    1200000
4267      12800000           8           780                    8200000
4268      29700000          10           607                   17800000

       commercial_assets_value   luxury_assets_value   bank_asset_value  \
0                     17600000              22700000            8000000
1                      2200000               8800000            3300000
2                      4500000              33300000           12800000
3                      3300000              23300000            7900000
4                      8200000              29400000            5000000
...                        ...                   ...                ...
4264                    500000               3300000             800000
4265                   2900000              11000000            1900000
4266                  12400000              18100000            7300000
4267                    700000              14100000            5800000
4268                  11800000              35700000           12000000

      loan_status
0        Approved
1        Rejected
2        Rejected
3        Rejected
4        Rejected
...           ...
4264     Rejected
4265     Approved
4266     Rejected
4267     Approved
4268     Approved

[4269 rows x 13 columns]

In [ ]:
print(df.sort_values(by='loan_id'))

      loan_id  no_of_dependents      education  self_employed   income_annum  \
0           1                 2       Graduate             No        9600000
1           2                 0   Not Graduate            Yes        4100000
2           3                 3       Graduate             No        9100000
3           4                 3       Graduate             No        8200000
4           5                 5   Not Graduate            Yes        9800000
...       ...               ...            ...            ...            ...
4264     4265                 5       Graduate            Yes        1000000
4265     4266                 0   Not Graduate            Yes        3300000
4266     4267                 2   Not Graduate             No        6500000
4267     4268                 1   Not Graduate             No        4100000
4268     4269                 1       Graduate             No        9200000

       loan_amount   loan_term   cibil_score   residential_assets_value  \
0         29900000          12           778                    2400000
1         12200000           8           417                    2700000
2         29700000          20           506                    7100000
3         30700000           8           467                   18200000
4         24200000          20           382                   12400000
...            ...         ...           ...                        ...
4264       2300000          12           317                    2800000
4265      11300000          20           559                    4200000
4266      23900000          18           457                    1200000
4267      12800000           8           780                    8200000
4268      29700000          10           607                   17800000

       commercial_assets_value   luxury_assets_value   bank_asset_value  \
0                     17600000              22700000            8000000
1                      2200000               8800000            3300000
2                      4500000              33300000           12800000
3                      3300000              23300000            7900000
4                      8200000              29400000            5000000
...                        ...                   ...                ...
4264                    500000               3300000             800000
4265                   2900000              11000000            1900000
4266                  12400000              18100000            7300000
4267                    700000              14100000            5800000
4268                  11800000              35700000           12000000

      loan_status
0        Approved
1        Rejected
2        Rejected
3        Rejected
4        Rejected
...           ...
4264     Rejected
4265     Approved
4266     Rejected
4267     Approved
4268     Approved

[4269 rows x 13 columns]

In [ ]:
print(df.isnull())

      loan_id  no_of_dependents   education   self_employed   income_annum  \
0       False             False       False           False          False
1       False             False       False           False          False
2       False             False       False           False          False
3       False             False       False           False          False
4       False             False       False           False          False
...       ...               ...         ...             ...            ...
4264    False             False       False           False          False
4265    False             False       False           False          False
4266    False             False       False           False          False
4267    False             False       False           False          False
4268    False             False       False           False          False

       loan_amount   loan_term   cibil_score   residential_assets_value  \
0            False       False         False                      False
1            False       False         False                      False
2            False       False         False                      False
3            False       False         False                      False
4            False       False         False                      False
...            ...         ...           ...                        ...
4264         False       False         False                      False
4265         False       False         False                      False
4266         False       False         False                      False
4267         False       False         False                      False
4268         False       False         False                      False

       commercial_assets_value   luxury_assets_value   bank_asset_value  \
0                        False                 False              False
1                        False                 False              False
2                        False                 False              False
3                        False                 False              False
4                        False                 False              False
...                        ...                   ...                ...
4264                     False                 False              False
4265                     False                 False              False
4266                     False                 False              False
4267                     False                 False              False
4268                     False                 False              False

       loan_status
0            False
1            False
2            False
3            False
4            False
...            ...
4264         False
4265         False
4266         False
4267         False
4268         False

[4269 rows x 13 columns]

In [ ]:
print(df.notnull())

      loan_id  no_of_dependents   education   self_employed   income_annum  \
0        True              True        True            True           True
1        True              True        True            True           True
2        True              True        True            True           True
3        True              True        True            True           True
4        True              True        True            True           True
...       ...               ...         ...             ...            ...
4264     True              True        True            True           True
4265     True              True        True            True           True
4266     True              True        True            True           True
4267     True              True        True            True           True
4268     True              True        True            True           True

       loan_amount   loan_term   cibil_score   residential_assets_value  \
0             True        True          True                       True
1             True        True          True                       True
2             True        True          True                       True
3             True        True          True                       True
4             True        True          True                       True
...            ...         ...           ...                        ...
4264          True        True          True                       True
4265          True        True          True                       True
4266          True        True          True                       True
4267          True        True          True                       True
4268          True        True          True                       True

       commercial_assets_value   luxury_assets_value   bank_asset_value  \
0                         True                  True               True
1                         True                  True               True
2                         True                  True               True
3                         True                  True               True
4                         True                  True               True
...                        ...                   ...                ...
4264                      True                  True               True
4265                      True                  True               True
4266                      True                  True               True
4267                      True                  True               True
4268                      True                  True               True

       loan_status
0             True
1             True
2             True
3             True
4             True
...            ...
4264          True
4265          True
4266          True
4267          True
4268          True

[4269 rows x 13 columns]

In [ ]:
print(df.duplicated())

0       False
1       False
2       False
3       False
4       False
        ...
4264    False
4265    False
4266    False
4267    False
4268    False
Length: 4269, dtype: bool

In [ ]:
print(df.sample())

     loan_id  no_of_dependents      education  self_employed   income_annum  \
875      876                 1   Not Graduate            Yes        1700000

      loan_amount   loan_term   cibil_score   residential_assets_value  \
875       4500000          20           480                     200000

      commercial_assets_value   luxury_assets_value   bank_asset_value  \
875                    600000               5400000            1900000

     loan_status
875     Rejected

In [ ]:
print(df.rename(columns={"cibil_score":"Credit Score"}))

      loan_id  no_of_dependents      education  self_employed   income_annum  \
0           1                 2       Graduate             No        9600000
1           2                 0   Not Graduate            Yes        4100000
2           3                 3       Graduate             No        9100000
3           4                 3       Graduate             No        8200000
4           5                 5   Not Graduate            Yes        9800000
...       ...               ...            ...            ...            ...
4264     4265                 5       Graduate            Yes        1000000
4265     4266                 0   Not Graduate            Yes        3300000
4266     4267                 2   Not Graduate             No        6500000
4267     4268                 1   Not Graduate             No        4100000
4268     4269                 1       Graduate             No        9200000

       loan_amount   loan_term   cibil_score   residential_assets_value  \
0         29900000          12           778                    2400000
1         12200000           8           417                    2700000
2         29700000          20           506                    7100000
3         30700000           8           467                   18200000
4         24200000          20           382                   12400000
...            ...         ...           ...                        ...
4264       2300000          12           317                    2800000
4265      11300000          20           559                    4200000
4266      23900000          18           457                    1200000
4267      12800000           8           780                    8200000
4268      29700000          10           607                   17800000

       commercial_assets_value   luxury_assets_value   bank_asset_value  \
0                     17600000              22700000            8000000
1                      2200000               8800000            3300000
2                      4500000              33300000           12800000
3                      3300000              23300000            7900000
4                      8200000              29400000            5000000
...                        ...                   ...                ...
4264                    500000               3300000             800000
4265                   2900000              11000000            1900000
4266                  12400000              18100000            7300000
4267                    700000              14100000            5800000
4268                  11800000              35700000           12000000

      loan_status
0        Approved
1        Rejected
2        Rejected
3        Rejected
4        Rejected
...           ...
4264     Rejected
4265     Approved
4266     Rejected
4267     Approved
4268     Approved

[4269 rows x 13 columns]

In [ ]:
print(df["loan_id"].mean())

2135.0

In [ ]:
print(df["loan_id"].median())

2135.0

In [ ]:
print(df["loan_id"].var())

1519052.5

In [ ]:
print(df["loan_id"].min())

1

In [ ]:
print(df["loan_id"].max())

4269

In [ ]:
print(df["loan_id"].sum())

9114315

In [ ]:
print(df["loan_id"].count())

4269

In [ ]:
print(df.groupby("loan_id").sum())

         no_of_dependents      education  self_employed   income_annum  \
loan_id
1                       2       Graduate             No        9600000
2                       0   Not Graduate            Yes        4100000
3                       3       Graduate             No        9100000
4                       3       Graduate             No        8200000
5                       5   Not Graduate            Yes        9800000
...                   ...            ...            ...            ...
4265                    5       Graduate            Yes        1000000
4266                    0   Not Graduate            Yes        3300000
4267                    2   Not Graduate             No        6500000
4268                    1   Not Graduate             No        4100000
4269                    1       Graduate             No        9200000

          loan_amount   loan_term   cibil_score   residential_assets_value  \
loan_id
1            29900000          12           778                    2400000
2            12200000           8           417                    2700000
3            29700000          20           506                    7100000
4            30700000           8           467                   18200000
5            24200000          20           382                   12400000
...               ...         ...           ...                        ...
4265          2300000          12           317                    2800000
4266         11300000          20           559                    4200000
4267         23900000          18           457                    1200000
4268         12800000           8           780                    8200000
4269         29700000          10           607                   17800000

          commercial_assets_value   luxury_assets_value   bank_asset_value  \
loan_id
1                        17600000              22700000            8000000
2                         2200000               8800000            3300000
3                         4500000              33300000           12800000
4                         3300000              23300000            7900000
5                         8200000              29400000            5000000
...                           ...                   ...                ...
4265                       500000               3300000             800000
4266                      2900000              11000000            1900000
4267                     12400000              18100000            7300000
4268                       700000              14100000            5800000
4269                     11800000              35700000           12000000

         loan_status
loan_id
1           Approved
2           Rejected
3           Rejected
4           Rejected
5           Rejected
...              ...
4265        Rejected
4266        Approved
4267        Rejected
4268        Approved
4269        Approved

[4269 rows x 12 columns]

In [ ]:
df.loc[len(df)] = [4270, 2, "Graduate", "No", 850000, 2500000, 15, 782, 4200000, 1500000, 900000, 600000, "Approved"]
print(df)

      loan_id  no_of_dependents      education  self_employed   income_annum  \
0           1                 2       Graduate             No        9600000
1           2                 0   Not Graduate            Yes        4100000
2           3                 3       Graduate             No        9100000
3           4                 3       Graduate             No        8200000
4           5                 5   Not Graduate            Yes        9800000
...       ...               ...            ...            ...            ...
4265     4266                 0   Not Graduate            Yes        3300000
4266     4267                 2   Not Graduate             No        6500000
4267     4268                 1   Not Graduate             No        4100000
4268     4269                 1       Graduate             No        9200000
4269     4270                 2       Graduate             No         850000

       loan_amount   loan_term   cibil_score   residential_assets_value  \
0         29900000          12           778                    2400000
1         12200000           8           417                    2700000
2         29700000          20           506                    7100000
3         30700000           8           467                   18200000
4         24200000          20           382                   12400000
...            ...         ...           ...                        ...
4265      11300000          20           559                    4200000
4266      23900000          18           457                    1200000
4267      12800000           8           780                    8200000
4268      29700000          10           607                   17800000
4269       2500000          15           782                    4200000

       commercial_assets_value   luxury_assets_value   bank_asset_value  \
0                     17600000              22700000            8000000
1                      2200000               8800000            3300000
2                      4500000              33300000           12800000
3                      3300000              23300000            7900000
4                      8200000              29400000            5000000
...                        ...                   ...                ...
4265                   2900000              11000000            1900000
4266                  12400000              18100000            7300000
4267                    700000              14100000            5800000
4268                  11800000              35700000           12000000
4269                   1500000                900000             600000

      loan_status
0        Approved
1        Rejected
2        Rejected
3        Rejected
4        Rejected
...           ...
4265     Approved
4266     Rejected
4267     Approved
4268     Approved
4269     Approved

[4270 rows x 13 columns]

In [ ]:
df = df.drop("no_of_dependents", axis = 1)
print(df)

      loan_id      education  self_employed   income_annum   loan_amount  \
0           1       Graduate             No        9600000      29900000
1           2   Not Graduate            Yes        4100000      12200000
2           3       Graduate             No        9100000      29700000
3           4       Graduate             No        8200000      30700000
4           5   Not Graduate            Yes        9800000      24200000
...       ...            ...            ...            ...           ...
4265     4266   Not Graduate            Yes        3300000      11300000
4266     4267   Not Graduate             No        6500000      23900000
4267     4268   Not Graduate             No        4100000      12800000
4268     4269       Graduate             No        9200000      29700000
4269     4270       Graduate             No         850000       2500000

       loan_term   cibil_score   residential_assets_value  \
0             12           778                    2400000
1              8           417                    2700000
2             20           506                    7100000
3              8           467                   18200000
4             20           382                   12400000
...          ...           ...                        ...
4265          20           559                    4200000
4266          18           457                    1200000
4267           8           780                    8200000
4268          10           607                   17800000
4269          15           782                    4200000

       commercial_assets_value   luxury_assets_value   bank_asset_value  \
0                     17600000              22700000            8000000
1                      2200000               8800000            3300000
2                      4500000              33300000           12800000
3                      3300000              23300000            7900000
4                      8200000              29400000            5000000
...                        ...                   ...                ...
4265                   2900000              11000000            1900000
4266                  12400000              18100000            7300000
4267                    700000              14100000            5800000
4268                  11800000              35700000           12000000
4269                   1500000                900000             600000

      loan_status
0        Approved
1        Rejected
2        Rejected
3        Rejected
4        Rejected
...           ...
4265     Approved
4266     Rejected
4267     Approved
4268     Approved
4269     Approved

[4270 rows x 12 columns]

In [ ]:
new = df.copy()
print(new)

      loan_id      education  self_employed   income_annum   loan_amount  \
0           1       Graduate             No        9600000      29900000
1           2   Not Graduate            Yes        4100000      12200000
2           3       Graduate             No        9100000      29700000
3           4       Graduate             No        8200000      30700000
4           5   Not Graduate            Yes        9800000      24200000
...       ...            ...            ...            ...           ...
4265     4266   Not Graduate            Yes        3300000      11300000
4266     4267   Not Graduate             No        6500000      23900000
4267     4268   Not Graduate             No        4100000      12800000
4268     4269       Graduate             No        9200000      29700000
4269     4270       Graduate             No         850000       2500000

       loan_term   cibil_score   residential_assets_value  \
0             12           778                    2400000
1              8           417                    2700000
2             20           506                    7100000
3              8           467                   18200000
4             20           382                   12400000
...          ...           ...                        ...
4265          20           559                    4200000
4266          18           457                    1200000
4267           8           780                    8200000
4268          10           607                   17800000
4269          15           782                    4200000

       commercial_assets_value   luxury_assets_value   bank_asset_value  \
0                     17600000              22700000            8000000
1                      2200000               8800000            3300000
2                      4500000              33300000           12800000
3                      3300000              23300000            7900000
4                      8200000              29400000            5000000
...                        ...                   ...                ...
4265                   2900000              11000000            1900000
4266                  12400000              18100000            7300000
4267                    700000              14100000            5800000
4268                  11800000              35700000           12000000
4269                   1500000                900000             600000

      loan_status
0        Approved
1        Rejected
2        Rejected
3        Rejected
4        Rejected
...           ...
4265     Approved
4266     Rejected
4267     Approved
4268     Approved
4269     Approved

[4270 rows x 12 columns]

In [ ]:
df = df.drop(df.index[-1])
print(df)

      loan_id      education  self_employed   income_annum   loan_amount  \
0           1       Graduate             No        9600000      29900000
1           2   Not Graduate            Yes        4100000      12200000
2           3       Graduate             No        9100000      29700000
3           4       Graduate             No        8200000      30700000
4           5   Not Graduate            Yes        9800000      24200000
...       ...            ...            ...            ...           ...
4264     4265       Graduate            Yes        1000000       2300000
4265     4266   Not Graduate            Yes        3300000      11300000
4266     4267   Not Graduate             No        6500000      23900000
4267     4268   Not Graduate             No        4100000      12800000
4268     4269       Graduate             No        9200000      29700000

       loan_term   cibil_score   residential_assets_value  \
0             12           778                    2400000
1              8           417                    2700000
2             20           506                    7100000
3              8           467                   18200000
4             20           382                   12400000
...          ...           ...                        ...
4264          12           317                    2800000
4265          20           559                    4200000
4266          18           457                    1200000
4267           8           780                    8200000
4268          10           607                   17800000

       commercial_assets_value   luxury_assets_value   bank_asset_value  \
0                     17600000              22700000            8000000
1                      2200000               8800000            3300000
2                      4500000              33300000           12800000
3                      3300000              23300000            7900000
4                      8200000              29400000            5000000
...                        ...                   ...                ...
4264                    500000               3300000             800000
4265                   2900000              11000000            1900000
4266                  12400000              18100000            7300000
4267                    700000              14100000            5800000
4268                  11800000              35700000           12000000

      loan_status
0        Approved
1        Rejected
2        Rejected
3        Rejected
4        Rejected
...           ...
4264     Rejected
4265     Approved
4266     Rejected
4267     Approved
4268     Approved

[4269 rows x 12 columns]

In [ ]:
df = df.replace(559,450)
print(df)

      loan_id      education  self_employed   income_annum   loan_amount  \
0           1       Graduate             No        9600000      29900000
1           2   Not Graduate            Yes        4100000      12200000
2           3       Graduate             No        9100000      29700000
3           4       Graduate             No        8200000      30700000
4           5   Not Graduate            Yes        9800000      24200000
...       ...            ...            ...            ...           ...
4264     4265       Graduate            Yes        1000000       2300000
4265     4266   Not Graduate            Yes        3300000      11300000
4266     4267   Not Graduate             No        6500000      23900000
4267     4268   Not Graduate             No        4100000      12800000
4268     4269       Graduate             No        9200000      29700000

       loan_term   cibil_score   residential_assets_value  \
0             12           778                    2400000
1              8           417                    2700000
2             20           506                    7100000
3              8           467                   18200000
4             20           382                   12400000
...          ...           ...                        ...
4264          12           317                    2800000
4265          20           450                    4200000
4266          18           457                    1200000
4267           8           780                    8200000
4268          10           607                   17800000

       commercial_assets_value   luxury_assets_value   bank_asset_value  \
0                     17600000              22700000            8000000
1                      2200000               8800000            3300000
2                      4500000              33300000           12800000
3                      3300000              23300000            7900000
4                      8200000              29400000            5000000
...                        ...                   ...                ...
4264                    500000               3300000             800000
4265                   2900000              11000000            1900000
4266                  12400000              18100000            7300000
4267                    700000              14100000            5800000
4268                  11800000              35700000           12000000

      loan_status
0        Approved
1        Rejected
2        Rejected
3        Rejected
4        Rejected
...           ...
4264     Rejected
4265     Approved
4266     Rejected
4267     Approved
4268     Approved

[4269 rows x 12 columns]

In [ ]:
df

,loan_id,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,2,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,4,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected
...,...,...,...,...,...,...,...,...,...,...,...,...
4264,4265,Graduate,Yes,1000000,2300000,12,317,2800000,500000,3300000,800000,Rejected
4265,4266,Not Graduate,Yes,3300000,11300000,20,450,4200000,2900000,11000000,1900000,Approved
4266,4267,Not Graduate,No,6500000,23900000,18,457,1200000,12400000,18100000,7300000,Rejected
4267,4268,Not Graduate,No,4100000,12800000,8,780,8200000,700000,14100000,5800000,Approved
4268,4269,Graduate,No,9200000,29700000,10,607,17800000,11800000,35700000,12000000,Approved

In [ ]:
df.columns = df.columns.str.strip()

In [ ]:
df["education"] = df["education"].str.upper()
print(df)

      loan_id      education self_employed  income_annum  loan_amount  \
0           1       GRADUATE            No       9600000     29900000
1           2   NOT GRADUATE           Yes       4100000     12200000
2           3       GRADUATE            No       9100000     29700000
3           4       GRADUATE            No       8200000     30700000
4           5   NOT GRADUATE           Yes       9800000     24200000
...       ...            ...           ...           ...          ...
4264     4265       GRADUATE           Yes       1000000      2300000
4265     4266   NOT GRADUATE           Yes       3300000     11300000
4266     4267   NOT GRADUATE            No       6500000     23900000
4267     4268   NOT GRADUATE            No       4100000     12800000
4268     4269       GRADUATE            No       9200000     29700000

      loan_term  cibil_score  residential_assets_value  \
0            12          778                   2400000
1             8          417                   2700000
2            20          506                   7100000
3             8          467                  18200000
4            20          382                  12400000
...         ...          ...                       ...
4264         12          317                   2800000
4265         20          450                   4200000
4266         18          457                   1200000
4267          8          780                   8200000
4268         10          607                  17800000

      commercial_assets_value  luxury_assets_value  bank_asset_value  \
0                    17600000             22700000           8000000
1                     2200000              8800000           3300000
2                     4500000             33300000          12800000
3                     3300000             23300000           7900000
4                     8200000             29400000           5000000
...                       ...                  ...               ...
4264                   500000              3300000            800000
4265                  2900000             11000000           1900000
4266                 12400000             18100000           7300000
4267                   700000             14100000           5800000
4268                 11800000             35700000          12000000

     loan_status
0       Approved
1       Rejected
2       Rejected
3       Rejected
4       Rejected
...          ...
4264    Rejected
4265    Approved
4266    Rejected
4267    Approved
4268    Approved

[4269 rows x 12 columns]

In [ ]:
df["education"] = df["education"].str.lower()
print(df)

      loan_id      education self_employed  income_annum  loan_amount  \
0           1       graduate            No       9600000     29900000
1           2   not graduate           Yes       4100000     12200000
2           3       graduate            No       9100000     29700000
3           4       graduate            No       8200000     30700000
4           5   not graduate           Yes       9800000     24200000
...       ...            ...           ...           ...          ...
4264     4265       graduate           Yes       1000000      2300000
4265     4266   not graduate           Yes       3300000     11300000
4266     4267   not graduate            No       6500000     23900000
4267     4268   not graduate            No       4100000     12800000
4268     4269       graduate            No       9200000     29700000

      loan_term  cibil_score  residential_assets_value  \
0            12          778                   2400000
1             8          417                   2700000
2            20          506                   7100000
3             8          467                  18200000
4            20          382                  12400000
...         ...          ...                       ...
4264         12          317                   2800000
4265         20          450                   4200000
4266         18          457                   1200000
4267          8          780                   8200000
4268         10          607                  17800000

      commercial_assets_value  luxury_assets_value  bank_asset_value  \
0                    17600000             22700000           8000000
1                     2200000              8800000           3300000
2                     4500000             33300000          12800000
3                     3300000             23300000           7900000
4                     8200000             29400000           5000000
...                       ...                  ...               ...
4264                   500000              3300000            800000
4265                  2900000             11000000           1900000
4266                 12400000             18100000           7300000
4267                   700000             14100000           5800000
4268                 11800000             35700000          12000000

     loan_status
0       Approved
1       Rejected
2       Rejected
3       Rejected
4       Rejected
...          ...
4264    Rejected
4265    Approved
4266    Rejected
4267    Approved
4268    Approved

[4269 rows x 12 columns]

In [ ]:
df.query('cibil_score > 800')

,loan_id,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
29,30,not graduate,Yes,9000000,31500000,10,850,21800000,12400000,33700000,8000000,Approved
33,34,not graduate,Yes,8400000,22000000,2,830,3800000,3900000,19900000,5400000,Approved
38,39,graduate,No,3600000,7700000,16,830,7000000,1300000,10000000,2900000,Approved
41,42,not graduate,No,9100000,24900000,16,822,22300000,12100000,31000000,5200000,Approved
55,56,not graduate,No,6700000,24500000,12,818,1200000,5600000,16300000,6200000,Approved
...,...,...,...,...,...,...,...,...,...,...,...,...
4247,4248,not graduate,No,3100000,9800000,12,820,6400000,5200000,10900000,4400000,Approved
4249,4250,graduate,No,1100000,4000000,14,887,2400000,1500000,4200000,1600000,Approved
4253,4254,graduate,Yes,7000000,26200000,12,896,13100000,6600000,23600000,5700000,Approved
4261,4262,graduate,Yes,3000000,7500000,6,881,1400000,4500000,6100000,2300000,Approved
4263,4264,graduate,No,5000000,12700000,14,865,4700000,8100000,19500000,6300000,Approved

In [ ]:
print(df.dtypes)

loan_id                      int64
education                   object
self_employed               object
income_annum                 int64
loan_amount                  int64
loan_term                    int64
cibil_score                  int64
residential_assets_value     int64
commercial_assets_value      int64
luxury_assets_value          int64
bank_asset_value             int64
loan_status                 object
dtype: object