In [ ]:
import pandas as pd
df = pd.read_excel('/content/loan_approval.xlsx')

In [ ]:
df

,name,city,income,credit_score,loan_amount,years_employed,points,loan_approved
0,Allison Hill,East Jill,113810,389,39698,27,50,False
1,Brandon Hall,New Jamesside,44592,729,15446,28,55,False
2,Rhonda Smith,Lake Roberto,33278,584,11189,13,45,False
3,Gabrielle Davis,West Melanieview,127196,344,48823,29,50,False
4,Valerie Gray,Mariastad,66048,496,47174,4,25,False
...,...,...,...,...,...,...,...,...
94,Juan Reyes,Port Chad,77819,724,23274,32,70,True
95,Aaron Barber,Grimesmouth,51319,795,23618,21,70,True
96,Kimberly Gibson,Mollybury,78520,692,16306,26,75,True
97,Patrick Thornton,Hughesberg,76566,807,3426,8,90,True
98,Leslie Kane,Garciamouth,57460,315,48346,9,30,False

In [ ]:
print(df.head())

              name              city  income  credit_score  loan_amount  \
0     Allison Hill         East Jill  113810           389        39698
1     Brandon Hall     New Jamesside   44592           729        15446
2     Rhonda Smith      Lake Roberto   33278           584        11189
3  Gabrielle Davis  West Melanieview  127196           344        48823
4     Valerie Gray         Mariastad   66048           496        47174

   years_employed  points  loan_approved
0              27      50          False
1              28      55          False
2              13      45          False
3              29      50          False
4               4      25          False

In [ ]:
print(df.tail())

                name         city  income  credit_score  loan_amount  \
94        Juan Reyes    Port Chad   77819           724        23274
95      Aaron Barber  Grimesmouth   51319           795        23618
96   Kimberly Gibson    Mollybury   78520           692        16306
97  Patrick Thornton   Hughesberg   76566           807         3426
98       Leslie Kane  Garciamouth   57460           315        48346

    years_employed  points  loan_approved
94              32      70           True
95              21      70           True
96              26      75           True
97               8      90           True
98               9      30          False

In [ ]:
print(df.shape)

(99, 8)

In [ ]:
print("\nColumn Names:")
print(df.columns)

Column Names:
Index(['name', 'city', 'income', 'credit_score', 'loan_amount',
       'years_employed', 'points', 'loan_approved'],
      dtype='object')

In [ ]:
print("\nDataset Information:")
print(df.info())

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            99 non-null     object
 1   city            99 non-null     object
 2   income          99 non-null     int64
 3   credit_score    99 non-null     int64
 4   loan_amount     99 non-null     int64
 5   years_employed  99 non-null     int64
 6   points          99 non-null     int64
 7   loan_approved   99 non-null     bool
dtypes: bool(1), int64(5), object(2)
memory usage: 5.6+ KB
None

In [ ]:
print("\nStatistical Summary:")
print(df.describe())

Statistical Summary:
              income  credit_score   loan_amount  years_employed      points
count      99.000000     99.000000     99.000000        99.00000   99.000000
mean    85448.505051    562.858586  24573.626263        20.69697   54.242424
std     35332.313128    159.989286  13608.600726        12.14660   17.266867
min     30851.000000    309.000000   1037.000000         0.00000   10.000000
25%     56761.000000    405.500000  13910.000000        11.00000   45.000000
50%     79615.000000    572.000000  23274.000000        21.00000   55.000000
75%    115927.000000    705.000000  35564.500000        31.50000   65.000000
max    146939.000000    843.000000  48823.000000        40.00000  100.000000

In [ ]:
print("\nAfter Removing Duplicates:")
print(df.drop_duplicates())

After Removing Duplicates:
                name              city  income  credit_score  loan_amount  \
0       Allison Hill         East Jill  113810           389        39698
1       Brandon Hall     New Jamesside   44592           729        15446
2       Rhonda Smith      Lake Roberto   33278           584        11189
3    Gabrielle Davis  West Melanieview  127196           344        48823
4       Valerie Gray         Mariastad   66048           496        47174
..               ...               ...     ...           ...          ...
94        Juan Reyes         Port Chad   77819           724        23274
95      Aaron Barber       Grimesmouth   51319           795        23618
96   Kimberly Gibson         Mollybury   78520           692        16306
97  Patrick Thornton        Hughesberg   76566           807         3426
98       Leslie Kane       Garciamouth   57460           315        48346

    years_employed  points  loan_approved
0               27      50          False
1               28      55          False
2               13      45          False
3               29      50          False
4                4      25          False
..             ...     ...            ...
94              32      70           True
95              21      70           True
96              26      75           True
97               8      90           True
98               9      30          False

[99 rows x 8 columns]

In [ ]:
print(df.sort_values(by='credit_score'))

                    name            city  income  credit_score  loan_amount  \
35           Mandy Green   Arnoldchester   66463           309         8331
70  Frederick Freeman MD     Matthewview  112397           310        34857
98           Leslie Kane     Garciamouth   57460           315        48346
64   Michelle Strickland     West Daniel   46361           326        21444
86          Darryl Craig  Port Emilyview   60512           341        12481
..                   ...             ...     ...           ...          ...
97      Patrick Thornton      Hughesberg   76566           807         3426
88          Frank Garcia     West Robert   43238           807        19888
90    Kimberly Gutierrez     New Michael   66434           810        41986
13        Jeffrey Chavez     Teresaburgh  101482           819         7973
14            Mark Lynch    West Kathryn   41395           843         1037

    years_employed  points  loan_approved
35               4      35          False
70              12      50          False
98               9      30          False
64              36      25          False
86              30      45          False
..             ...     ...            ...
97               8      90           True
88              25      65           True
90              28      75           True
13              40     100           True
14              38      80           True

[99 rows x 8 columns]

In [ ]:
print(df.isnull())

     name   city  income  credit_score  loan_amount  years_employed  points  \
0   False  False   False         False        False           False   False
1   False  False   False         False        False           False   False
2   False  False   False         False        False           False   False
3   False  False   False         False        False           False   False
4   False  False   False         False        False           False   False
..    ...    ...     ...           ...          ...             ...     ...
94  False  False   False         False        False           False   False
95  False  False   False         False        False           False   False
96  False  False   False         False        False           False   False
97  False  False   False         False        False           False   False
98  False  False   False         False        False           False   False

    loan_approved
0           False
1           False
2           False
3           False
4           False
..            ...
94          False
95          False
96          False
97          False
98          False

[99 rows x 8 columns]

In [ ]:
print(df.notnull())

    name  city  income  credit_score  loan_amount  years_employed  points  \
0   True  True    True          True         True            True    True
1   True  True    True          True         True            True    True
2   True  True    True          True         True            True    True
3   True  True    True          True         True            True    True
4   True  True    True          True         True            True    True
..   ...   ...     ...           ...          ...             ...     ...
94  True  True    True          True         True            True    True
95  True  True    True          True         True            True    True
96  True  True    True          True         True            True    True
97  True  True    True          True         True            True    True
98  True  True    True          True         True            True    True

    loan_approved
0            True
1            True
2            True
3            True
4            True
..            ...
94           True
95           True
96           True
97           True
98           True

[99 rows x 8 columns]

In [ ]:
print(df.duplicated())

0     False
1     False
2     False
3     False
4     False
      ...
94    False
95    False
96    False
97    False
98    False
Length: 99, dtype: bool

In [ ]:
print(df.sample())

            name       city  income  credit_score  loan_amount  \
10  Justin Baker  Hurstfurt  118696           670        15373

    years_employed  points  loan_approved
10               8      75           True

In [ ]:
print(df.rename(columns={"credit_score":"Credit Score"}))

                name              city  income  Credit Score  loan_amount  \
0       Allison Hill         East Jill  113810           389        39698
1       Brandon Hall     New Jamesside   44592           729        15446
2       Rhonda Smith      Lake Roberto   33278           584        11189
3    Gabrielle Davis  West Melanieview  127196           344        48823
4       Valerie Gray         Mariastad   66048           496        47174
..               ...               ...     ...           ...          ...
94        Juan Reyes         Port Chad   77819           724        23274
95      Aaron Barber       Grimesmouth   51319           795        23618
96   Kimberly Gibson         Mollybury   78520           692        16306
97  Patrick Thornton        Hughesberg   76566           807         3426
98       Leslie Kane       Garciamouth   57460           315        48346

    years_employed  points  loan_approved
0               27      50          False
1               28      55          False
2               13      45          False
3               29      50          False
4                4      25          False
..             ...     ...            ...
94              32      70           True
95              21      70           True
96              26      75           True
97               8      90           True
98               9      30          False

[99 rows x 8 columns]

In [ ]:
print(df["credit_score"].mean())

562.8585858585859

In [ ]:
print(df["credit_score"].median())

572.0

In [ ]:
print(df["credit_score"].var())

25596.571634714503

In [ ]:
print(df["credit_score"].min())

309

In [ ]:
print(df["credit_score"].max())

843

In [ ]:
print(df["credit_score"].sum())

55723

In [ ]:
print(df["credit_score"].count())

99

In [ ]:
print(df.groupby("credit_score").sum())

                                      name                      city  income  \
credit_score
309                            Mandy Green             Arnoldchester   66463
310                   Frederick Freeman MD               Matthewview  112397
315                            Leslie Kane               Garciamouth   57460
326                    Michelle Strickland               West Daniel   46361
341                           Darryl Craig            Port Emilyview   60512
...                                    ...                       ...     ...
802              Nathan FreemanJoseph Hill  Lake ThomasNew Kellyberg  166273
807           Frank GarciaPatrick Thornton     West RobertHughesberg  119804
810                     Kimberly Gutierrez               New Michael   66434
819                         Jeffrey Chavez               Teresaburgh  101482
843                             Mark Lynch              West Kathryn   41395

              loan_amount  years_employed  points  loan_approved
credit_score
309                  8331               4      35              0
310                 34857              12      50              0
315                 48346               9      30              0
326                 21444              36      25              0
341                 12481              30      45              0
...                   ...             ...     ...            ...
802                 38094               1     145              2
807                 23314              33     155              2
810                 41986              28      75              1
819                  7973              40     100              1
843                  1037              38      80              1

[88 rows x 7 columns]

In [ ]:
df

,name,city,income,credit_score,loan_amount,years_employed,points,loan_approved
0,Allison Hill,East Jill,113810,389,39698,27,50,False
1,Brandon Hall,New Jamesside,44592,729,15446,28,55,False
2,Rhonda Smith,Lake Roberto,33278,584,11189,13,45,False
3,Gabrielle Davis,West Melanieview,127196,344,48823,29,50,False
4,Valerie Gray,Mariastad,66048,496,47174,4,25,False
...,...,...,...,...,...,...,...,...
94,Juan Reyes,Port Chad,77819,724,23274,32,70,True
95,Aaron Barber,Grimesmouth,51319,795,23618,21,70,True
96,Kimberly Gibson,Mollybury,78520,692,16306,26,75,True
97,Patrick Thornton,Hughesberg,76566,807,3426,8,90,True
98,Leslie Kane,Garciamouth,57460,315,48346,9,30,False

In [ ]:
df.loc[len(df)] = ["Roshan", "Chennai", 69000, 780, 20000, 10, 50, "True"]
print(df)

                name              city  income  credit_score  loan_amount  \
0       Allison Hill         East Jill  113810           389        39698
1       Brandon Hall     New Jamesside   44592           729        15446
2       Rhonda Smith      Lake Roberto   33278           584        11189
3    Gabrielle Davis  West Melanieview  127196           344        48823
4       Valerie Gray         Mariastad   66048           496        47174
..               ...               ...     ...           ...          ...
95      Aaron Barber       Grimesmouth   51319           795        23618
96   Kimberly Gibson         Mollybury   78520           692        16306
97  Patrick Thornton        Hughesberg   76566           807         3426
98       Leslie Kane       Garciamouth   57460           315        48346
99            Roshan           Chennai   69000           780        20000

    years_employed  points loan_approved
0               27      50         False
1               28      55         False
2               13      45         False
3               29      50         False
4                4      25         False
..             ...     ...           ...
95              21      70          True
96              26      75          True
97               8      90          True
98               9      30         False
99              10      50          True

[100 rows x 8 columns]

In [ ]:
df = df.drop("points", axis = 1)
print(df)

                name              city  income  credit_score  loan_amount  \
0       Allison Hill         East Jill  113810           389        39698
1       Brandon Hall     New Jamesside   44592           729        15446
2       Rhonda Smith      Lake Roberto   33278           584        11189
3    Gabrielle Davis  West Melanieview  127196           344        48823
4       Valerie Gray         Mariastad   66048           496        47174
..               ...               ...     ...           ...          ...
95      Aaron Barber       Grimesmouth   51319           795        23618
96   Kimberly Gibson         Mollybury   78520           692        16306
97  Patrick Thornton        Hughesberg   76566           807         3426
98       Leslie Kane       Garciamouth   57460           315        48346
99            Roshan           Chennai   69000           780        20000

    years_employed loan_approved
0               27         False
1               28         False
2               13         False
3               29         False
4                4         False
..             ...           ...
95              21          True
96              26          True
97               8          True
98               9         False
99              10          True

[100 rows x 7 columns]

In [ ]:
new = df.copy()
print(new)

                name              city  income  credit_score  loan_amount  \
0       Allison Hill         East Jill  113810           389        39698
1       Brandon Hall     New Jamesside   44592           729        15446
2       Rhonda Smith      Lake Roberto   33278           584        11189
3    Gabrielle Davis  West Melanieview  127196           344        48823
4       Valerie Gray         Mariastad   66048           496        47174
..               ...               ...     ...           ...          ...
95      Aaron Barber       Grimesmouth   51319           795        23618
96   Kimberly Gibson         Mollybury   78520           692        16306
97  Patrick Thornton        Hughesberg   76566           807         3426
98       Leslie Kane       Garciamouth   57460           315        48346
99            Roshan           Chennai   69000           780        20000

    years_employed loan_approved
0               27         False
1               28         False
2               13         False
3               29         False
4                4         False
..             ...           ...
95              21          True
96              26          True
97               8          True
98               9         False
99              10          True

[100 rows x 7 columns]

In [ ]:
df = df.drop(df.index[-1])
print(df)

                name              city  income  credit_score  loan_amount  \
0       Allison Hill         East Jill  113810           389        39698
1       Brandon Hall     New Jamesside   44592           729        15446
2       Rhonda Smith      Lake Roberto   33278           584        11189
3    Gabrielle Davis  West Melanieview  127196           344        48823
4       Valerie Gray         Mariastad   66048           496        47174
..               ...               ...     ...           ...          ...
94        Juan Reyes         Port Chad   77819           724        23274
95      Aaron Barber       Grimesmouth   51319           795        23618
96   Kimberly Gibson         Mollybury   78520           692        16306
97  Patrick Thornton        Hughesberg   76566           807         3426
98       Leslie Kane       Garciamouth   57460           315        48346

    years_employed loan_approved
0               27         False
1               28         False
2               13         False
3               29         False
4                4         False
..             ...           ...
94              32          True
95              21          True
96              26          True
97               8          True
98               9         False

[99 rows x 7 columns]

In [ ]:
df = df.replace(389,450)
print(df)

                name              city  income  credit_score  loan_amount  \
0       Allison Hill         East Jill  113810           450        39698
1       Brandon Hall     New Jamesside   44592           729        15446
2       Rhonda Smith      Lake Roberto   33278           584        11189
3    Gabrielle Davis  West Melanieview  127196           344        48823
4       Valerie Gray         Mariastad   66048           496        47174
..               ...               ...     ...           ...          ...
94        Juan Reyes         Port Chad   77819           724        23274
95      Aaron Barber       Grimesmouth   51319           795        23618
96   Kimberly Gibson         Mollybury   78520           692        16306
97  Patrick Thornton        Hughesberg   76566           807         3426
98       Leslie Kane       Garciamouth   57460           315        48346

    years_employed loan_approved
0               27         False
1               28         False
2               13         False
3               29         False
4                4         False
..             ...           ...
94              32          True
95              21          True
96              26          True
97               8          True
98               9         False

[99 rows x 7 columns]

In [ ]:
df["name"] = df["name"].str.upper()

In [ ]:
df

,name,city,income,credit_score,loan_amount,years_employed,loan_approved
0,ALLISON HILL,East Jill,113810,450,39698,27,False
1,BRANDON HALL,New Jamesside,44592,729,15446,28,False
2,RHONDA SMITH,Lake Roberto,33278,584,11189,13,False
3,GABRIELLE DAVIS,West Melanieview,127196,344,48823,29,False
4,VALERIE GRAY,Mariastad,66048,496,47174,4,False
...,...,...,...,...,...,...,...
94,JUAN REYES,Port Chad,77819,724,23274,32,True
95,AARON BARBER,Grimesmouth,51319,795,23618,21,True
96,KIMBERLY GIBSON,Mollybury,78520,692,16306,26,True
97,PATRICK THORNTON,Hughesberg,76566,807,3426,8,True
98,LESLIE KANE,Garciamouth,57460,315,48346,9,False

In [ ]:
df["name"] = df["name"].str.lower()

In [ ]:
df

,name,city,income,credit_score,loan_amount,years_employed,loan_approved
0,allison hill,East Jill,113810,450,39698,27,False
1,brandon hall,New Jamesside,44592,729,15446,28,False
2,rhonda smith,Lake Roberto,33278,584,11189,13,False
3,gabrielle davis,West Melanieview,127196,344,48823,29,False
4,valerie gray,Mariastad,66048,496,47174,4,False
...,...,...,...,...,...,...,...
94,juan reyes,Port Chad,77819,724,23274,32,True
95,aaron barber,Grimesmouth,51319,795,23618,21,True
96,kimberly gibson,Mollybury,78520,692,16306,26,True
97,patrick thornton,Hughesberg,76566,807,3426,8,True
98,leslie kane,Garciamouth,57460,315,48346,9,False

In [ ]:
df.query('credit_score > 800')

,name,city,income,credit_score,loan_amount,years_employed,loan_approved
13,jeffrey chavez,Teresaburgh,101482,819,7973,40,True
14,mark lynch,West Kathryn,41395,843,1037,38,True
71,nathan freeman,Lake Thomas,111070,802,30371,1,True
76,joseph hill,New Kellyberg,55203,802,7723,0,True
88,frank garcia,West Robert,43238,807,19888,25,True
90,kimberly gutierrez,New Michael,66434,810,41986,28,True
97,patrick thornton,Hughesberg,76566,807,3426,8,True

In [ ]:
print(df.dtypes)

name              object
city              object
income             int64
credit_score       int64
loan_amount        int64
years_employed     int64
loan_approved     object
dtype: object