In [ ]:
import pandas as pd
df = pd.read_excel('/content/Student.xlsx')

In [ ]:
df

  Student Name  Sub1  Sub2
0        Pooja    99    98
1       Monesh    98    99
2     Karishma    97    98
3     Immaenul    98    97

In [ ]:
df.insert(3, "Sub3", [95, 96, 97, 98])
print(df)

  Student Name  Sub1  Sub2  Sub3
0        Pooja    99    98    95
1       Monesh    98    99    96
2     Karishma    97    98    97
3     Immaenul    98    97    98

In [ ]:
df.loc[len(df)] = ["Roshan", 99, 99, 99]
print(df)

  Student Name  Sub1  Sub2  Sub3
0        Pooja    99    98    95
1       Monesh    98    99    96
2     Karishma    97    98    97
3     Immaenul    98    97    98
4       Roshan    99    99    99
5       Roshan    99    99    99

In [ ]:
df = df.drop("Sub1", axis = 1)
print(df)

  Student Name  Sub2  Sub3
0        Pooja    98    95
1       Monesh    99    96
2     Karishma    98    97
3     Immaenul    97    98
4       Roshan    99    99
5       Roshan    99    99

In [ ]:
df

  Student Name  Sub2  Sub3
0        Pooja    98    95
1       Monesh    99    96
2     Karishma    98    97
3     Immaenul    97    98
4       Roshan    99    99
5       Roshan    99    99

In [ ]:
df = df.drop(df.index[-1])
print(df)

  Student Name  Sub2  Sub3
0        Pooja    98    95
1       Monesh    99    96
2     Karishma    98    97
3     Immaenul    97    98

In [ ]:
df = df.replace(97,98)
print(df)

  Student Name  Sub2  Sub3
0        Pooja    98    95
1       Monesh    99    96
2     Karishma    98    98
3     Immaenul    98    98

In [ ]:
df["Student Name"] = df["Student Name"].str.lower()

In [ ]:
df

  Student Name  Sub2  Sub3
0        pooja    98    95
1       monesh    99    96
2     karishma    98    98
3     immaenul    98    98

In [ ]:
df["Student Name"] = df["Student Name"].str.upper()

In [ ]:
df

  Student Name  Sub2  Sub3
0        POOJA    98    95
1       MONESH    99    96
2     KARISHMA    98    98
3     IMMAENUL    98    98